name: studora_backend
description: Dart Appwrite serverless functions used as backend logic for the Studora app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_appwrite: ^20.0.0
  http: ^1.2.0
